# Generated by Django 5.0.14 on 2026-09-21 13:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class, e.g. bi-cup-hot', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(help_text='What this campaign is about.')),
                ('instructions', models.TextField(blank=True, help_text='Step-by-step instructions for the reviewer.')),
                ('campaign_type', models.CharField(choices=[('REVIEW', 'Review'), ('SURVEY', 'Survey'), ('MYSTERY_SHOPPING', 'Mystery Shopping'), ('PRODUCT_TESTING', 'Product Testing'), ('SERVICE_TESTING', 'Service Testing')], default='SURVEY', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending approval'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=24)),
                ('reward_amount_ksh', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_participants', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('filled_slots', models.PositiveIntegerField(default=0)),
                ('budget_total_ksh', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_fee_ksh', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location_description', models.CharField(blank=True, max_length=160)),
                ('estimated_minutes', models.PositiveIntegerField(default=10, help_text='Estimated time to complete, in minutes.')),
                ('min_days_since_experience', models.PositiveIntegerField(default=30, help_text='How recent the experience must be.')),
                ('required_evidence_types', models.JSONField(blank=True, default=list, help_text="List of evidence type codes, e.g. ['RECEIPT', 'PHOTOGRAPH'].")),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='businesses.business')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='geo.county')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=400)),
                ('question_type', models.CharField(choices=[('TEXT', 'Short text'), ('LONG_TEXT', 'Long text'), ('SINGLE_CHOICE', 'Single choice'), ('MULTI_CHOICE', 'Multiple choice'), ('RATING', 'Rating (1-5)'), ('YES_NO', 'Yes / No'), ('NUMBER', 'Number')], default='TEXT', max_length=24)),
                ('options', models.JSONField(blank=True, default=list, help_text='For choice types: list of option strings.')),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['order', 'text'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['order', 'text'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'end_date'], name='campaigns_c_status_3c585c_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['category', 'status'], name='campaigns_c_categor_ea2d6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(check=models.Q(('filled_slots__lte', models.F('target_participants'))), name='campaign_filled_not_exceed_target'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='campaign_end_after_start'),
        ),
    ]
