# Generated by Django 5.2.17 on 2026-10-01 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_alter_business_owner"),
        ("campaigns", "0002_alter_campaign_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="businesses.business",
            ),
        ),
    ]
