# Generated by Django 5.2.17 on 2026-09-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaignapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_seed_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
