# Generated by Django 5.2.17 on 2026-09-22 12:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0003_campaignapplication'),
        ('geo', '0002_seed_kenya'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('trust_score', models.PositiveSmallIntegerField(default=50)),
                ('total_completed_tasks', models.PositiveIntegerField(default=0)),
                ('total_earnings_ksh', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_profiles', to='geo.county')),
                ('preferred_categories', models.ManyToManyField(blank=True, related_name='interested_reviewers', to='campaigns.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reviewer profile',
                'verbose_name_plural': 'Reviewer profiles',
            },
        ),
    ]
