# Generated by Django 5.2.17 on 2026-09-23 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewers', '0003_reviewerprofile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewerprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='reviewerprofile',
            name='county',
        ),
    ]
