# Generated by Django 5.2.17 on 2026-10-01 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_seed_countries"),
        ("reviewers", "0004_remove_reviewerprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewerprofile",
            name="country",
            field=models.ForeignKey(
                blank=True,
                help_text="Country where the reviewer is based.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewer_profiles",
                to="geo.country",
            ),
        ),
    ]
