# Generated by Django 5.2.17 on 2026-10-01 15:10

from django.conf import settings
from django.db import migrations, models


def invalidate_unbound_phone_verifications(apps, schema_editor):
    Payment = apps.get_model("payments", "Payment")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    database = schema_editor.connection.alias
    legacy_verifications = Payment.objects.using(database).filter(
        purpose="MPESA_ACCOUNT_VERIFICATION",
        phone_number="",
    )
    verified_user_ids = legacy_verifications.filter(status="SUCCESS").values_list(
        "user_id",
        flat=True,
    )
    User.objects.using(database).filter(pk__in=verified_user_ids).update(
        is_phone_verified=False,
    )
    legacy_verifications.filter(status="QUEUED").update(
        status="FAILED",
        failure_reason="Restart verification; the prompted phone number was not recorded.",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_alter_payment_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(
            invalidate_unbound_phone_verifications,
            migrations.RunPython.noop,
        ),
    ]
