# Generated by Django 5.2.17 on 2026-09-23 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_withheld', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('provider', models.CharField(choices=[('MPESA', 'M-Pesa'), ('PAYPAL', 'PayPal'), ('CARD', 'Card'), ('MANUAL', 'Manual')], default='MPESA', max_length=16)),
                ('destination_phone', models.CharField(blank=True, max_length=20)),
                ('destination_email', models.EmailField(blank=True, max_length=254)),
                ('provider_reference', models.CharField(blank=True, max_length=80)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=80, unique=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='withdrawals_user_id_add96e_idx'), models.Index(fields=['status', '-requested_at'], name='withdrawals_status_acb258_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='withdrawal_amount_positive'), models.CheckConstraint(condition=models.Q(('net_amount__gt', 0)), name='withdrawal_net_positive')],
            },
        ),
    ]
