# Generated by Django 5.2.17 on 2026-09-21 20:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_balance_ksh', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_balance_ksh', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lifetime_earnings_ksh', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lifetime_withdrawn_ksh', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('TASK_REWARD', 'Task reward'), ('WITHDRAWAL', 'Withdrawal'), ('WITHDRAWAL_REVERSAL', 'Withdrawal reversal'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment'), ('BONUS', 'Bonus'), ('FEE', 'Fee')], max_length=24)),
                ('amount_ksh', models.DecimalField(decimal_places=2, help_text='Signed: positive = credit, negative = debit.', max_digits=12)),
                ('balance_after_ksh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('idempotency_key', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('available_balance_ksh__gte', 0)), name='wallet_available_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('pending_balance_ksh__gte', 0)), name='wallet_pending_nonneg'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='wallets_wal_wallet__ed7753_idx'),
        ),
    ]
