# Generated by Django 5.0.14 on 2026-09-21 13:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2, e.g. KE', max_length=2, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('currency_code', models.CharField(default='KES', max_length=3)),
                ('phone_prefix', models.CharField(default='+254', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='geo.country')),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
                'unique_together': {('country', 'name')},
            },
        ),
    ]
